# -*- coding: utf-8 -*-
"""POCER의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CyipsqSGbfGYfQwWtCrKQDDYxrIMzJWI
"""

import pandas as pd
import numpy as np
import sys
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.special import inv_boxcox
from scipy import stats
import joblib
from matplotlib.ticker import FormatStrFormatter
import matplotlib.ticker as ticker
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

path = 'final.csv'
raw_data = pd.read_csv(path)
data = raw_data.dropna()
data.drop(['Feeding_rate', 'Active_vol'], axis = 1, inplace = True)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,6), dpi=350)
cmap = sns.diverging_palette(h_neg=10, h_pos=240,as_cmap=True)
mask = np.triu(np.ones_like(data.corr(), dtype=bool))
sns.heatmap(data.corr(), mask=mask, center=0, cmap=cmap, linewidths=0.8, annot=True, fmt='.2f', cbar=True, )
plt.show()
plt.clf()

#feature and target
raw_target = data[['specific_OLR']]
raw_features = data.drop('specific_OLR', axis = 1)
diff =5
features = raw_features.drop(range(0,diff))
features.reset_index(inplace = True, drop = True)
target = raw_target.drop(range(len(raw_target)-1, len(raw_target)-1 - diff, -1))
target.reset_index(inplace = True, drop = True)
df = pd.concat([target, features], axis =1)
plt.figure(figsize=(10,6), dpi=350)
cmap = sns.diverging_palette(h_neg=10, h_pos=240,as_cmap=True)
mask = np.triu(np.ones_like(df.corr(), dtype=bool))
sns.heatmap(df.corr(), mask=mask, center=0, cmap=cmap, linewidths=0.8, annot=True, fmt='.2f', cbar=True)
sns.set(font_scale = 0.5)
plt.show()
plt.clf()

data_filtered = data[['Feeding_vol','[S]_COD', 'pH', 'COD', 'TS', 'sCOD', 'sTOC', 'Biogas_PR', 'Tube_change'  ]]
test_filtered = test[['Feeding_vol','[S]_COD', 'pH', 'COD', 'TS', 'sCOD', 'sTOC', 'Biogas_PR', 'Tube_change'  ]]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(data_filtered)
x_test = scaler.transform(test_filtered)
prev_y = X_scaled[:,0]
prev_y_test = x_test[:,0]

def generator(y,timestep = 2):
  X = []
  for i in range(timestep):
      y_indices = range(i,len(y)-timestep+i)
      y_tmp = y[y_indices]
      X.append(y_tmp)
  
  return np.stack((X[0], X[1]), axis=1), y[range(timestep,len(y))]

prev_y, target = generator(prev_y)
prev_y_test, y_test = generator(prev_y_test)
#target.reset_index(inplace = True, drop = True)

#index differentiation
def X_generator(X_scaled, prev_y, diff = 1, timestep = 2):
  features = X_scaled[range(timestep - diff, len(X_scaled) - 1)]
  features = np.append(features, prev_y, axis =1)
  return features

features = X_generator(X_scaled, prev_y)
X_test = X_generator(x_test, prev_y_test)

from sklearn.decomposition import PCA
import plotly.express as px
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
prev_y, target = generator(X_scaled[:,0])
prev_y_test, y_test = generator(x_test[:,0])
features = X_generator(X_scaled, prev_y)
X_test = X_generator(x_test, prev_y_test)

pca = PCA(n_components=5)
printcipalComponents = pca.fit_transform(features)
principalDf = pd.DataFrame(data=printcipalComponents, columns = ['pc1', 'pc2', 'pc3', 'pc4', 'pc5'])
exp_var_cumul = np.cumsum(pca.explained_variance_ratio_)
test_PCA = pd.DataFrame(data=pca.transform(X_test), columns = ['pc1', 'pc2', 'pc3', 'pc4', 'pc5'])

labels = {
    str(i): f"PC {i+1} ({var:.1f}%)"
    for i, var in enumerate(pca.explained_variance_ratio_ * 100)
}
fig = px.scatter_matrix(
    printcipalComponents,
    labels=labels,
    dimensions=range(5),
    color=y_test
)
fig.update_traces(diagonal_visible=False)
fig.show()

px.area(
    x=range(1, exp_var_cumul.shape[0] + 1),
    y=exp_var_cumul,
    labels={"x": "# Components", "y": "Explained Variance"}
)

#model (many to one RNN)
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers, Input
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense, LSTM, TimeDistributed, Flatten
import tensorflow as tf
from keras.metrics import mean_squared_error

def train_val_split(features, target):
  X_train = features[:60]
  y_train = target[:60]
  X_val = features[60:]
  y_val = target[60:]
  return X_train,y_train, X_val, y_val
X_train,y_train, X_val, y_val = train_val_split(principalDf, target)

from keras.callbacks import EarlyStopping
earlystopping = EarlyStopping(monitor='val_loss',  # 모니터 기준 설정 (val loss) 
                              patience=10,         # 10회 Epoch동안 개선되지 않는다면 종료
                             )
model = Sequential([
                   SimpleRNN(units=20, return_sequences=True,input_shape = [None,1], ),
                   SimpleRNN(units=20, return_sequences=True),
                   SimpleRNN(units=20, return_sequences=True),
                   SimpleRNN(units=1),
])
model.compile(optimizer='adam', # default='rmsprop', an algorithm to be used in backpropagation
              loss='mean_squared_error', # Loss function to be optimized. A string (name of loss function), or a tf.keras.losses.Loss instance.
              #metrics=[r2, 'MeanSquaredError'], # List of metrics to be evaluated by the model during training and testing. Each of this can be a string (name of a built-in function), function or a tf.keras.metrics.Metric instance. 
              loss_weights=None, # default=None, Optional list or dictionary specifying scalar coefficients (Python floats) to weight the loss contributions of different model outputs.
              weighted_metrics=None, # default=None, List of metrics to be evaluated and weighted by sample_weight or class_weight during training and testing.
              run_eagerly=None, # Defaults to False. If True, this Model's logic will not be wrapped in a tf.function. Recommended to leave this as None unless your Model cannot be run inside a tf.function.
              steps_per_execution=None # Defaults to 1. The number of batches to run during each tf.function call. Running multiple batches inside a single tf.function call can greatly improve performance on TPUs or small models with a large Python overhead.
             )

history_RNN_PCA = model.fit(X_train, # input data
          y_train, # target data
          batch_size=5, # Number of samples per gradient update. If unspecified, batch_size will default to 32.
          epochs=200, # default=1, Number of epochs to train the model. An epoch is an iteration over the entire x and y data provided
          verbose=2, # default='auto', ('auto', 0, 1, or 2). Verbosity mode. 0 = silent, 1 = progress bar, 2 = one line per epoch. 'auto' defaults to 1 for most cases, but 2 when used with ParameterServerStrategy.
          callbacks=earlystopping, # default=None, list of callbacks to apply during training. See tf.keras.callbacks
          validation_data=(X_val, y_val), # default=0.0, Fraction of the training data to be used as validation data. The model will set apart this fraction of the training data, will not train on it, and will evaluate the loss and any model metrics on this data at the end of each epoch. 
          #validation_data=(X_test, y_test), # default=None, Data on which to evaluate the loss and any model metrics at the end of each epoch. 
          shuffle=True, # default=True, Boolean (whether to shuffle the training data before each epoch) or str (for 'batch').
          class_weight=None, # default=None, Optional dictionary mapping class indices (integers) to a weight (float) value, used for weighting the loss function (during training only). This can be useful to tell the model to "pay more attention" to samples from an under-represented class.
          sample_weight=None, # default=None, Optional Numpy array of weights for the training samples, used for weighting the loss function (during training only).
          initial_epoch=0, # Integer, default=0, Epoch at which to start training (useful for resuming a previous training run).
          steps_per_epoch=None, # Integer or None, default=None, Total number of steps (batches of samples) before declaring one epoch finished and starting the next epoch. When training with input tensors such as TensorFlow data tensors, the default None is equal to the number of samples in your dataset divided by the batch size, or 1 if that cannot be determined. 
          validation_steps=None, # Only relevant if validation_data is provided and is a tf.data dataset. Total number of steps (batches of samples) to draw before stopping when performing validation at the end of every epoch.
          validation_batch_size=None, # Integer or None, default=None, Number of samples per validation batch. If unspecified, will default to batch_size.
          validation_freq=1, # default=1, Only relevant if validation data is provided. If an integer, specifies how many training epochs to run before a new validation run is performed, e.g. validation_freq=2 runs validation every 2 epochs.
          max_queue_size=10, # default=10, Used for generator or keras.utils.Sequence input only. Maximum size for the generator queue. If unspecified, max_queue_size will default to 10.
          workers=1, # default=1, Used for generator or keras.utils.Sequence input only. Maximum number of processes to spin up when using process-based threading. If unspecified, workers will default to 1.
          use_multiprocessing=False, # default=False, Used for generator or keras.utils.Sequence input only. If True, use process-based threading. If unspecified, use_multiprocessing will default to False. 
         )

from sklearn.metrics import r2_score 

y_predict = model.predict(X_train)
r2_y_predict = r2_score(y_train, y_predict) 
print("R2 :", r2_y_predict)
model.evaluate(X_train, y_train)

# Visualization
import plotly 
import plotly.express as px
import plotly.graph_objects as go
print('plotly: %s' % plotly.__version__) # print version

fig = go.Figure()
'''
fig.add_trace(go.Scatter(x=np.array(range(0,len(history_RNN.history))),
                         y=history_RNN.history['loss'],
                         mode='lines',
                         name='RNN',
                         line=dict(color='blue', width=2),
                         opacity= 0.8
                        ))
fig.add_trace(go.Scatter(x=np.array(range(0,len(history_RNN.history))),
                         y=history_RNN.history['val_loss'],
                         mode='lines',
                         name='RNN',
                         line=dict(color='blue', width=1, shape = 'spline'),
                         opacity= 0.8
                        ))
'''
fig.add_trace(go.Scatter(x=np.array(range(0,len(history_RNN_PCA.history))),
                         y=history_RNN_PCA.history['loss'],
                         mode='lines',
                         name='RNN_PCA',
                         line=dict(color='red', width=2),
                         opacity= 0.8
                         
                        ))
fig.add_trace(go.Scatter(x=np.array(range(0,len(history_RNN_PCA.history))),
                         y=history_RNN_PCA.history['val_loss'],
                         mode='lines',
                         name='RNN_PCA',
                         line=dict(color='red', width=1, shape = 'spline'),
                         opacity= 0.8
                         
                        ))

# Change chart background color
fig.update_layout(dict(plot_bgcolor = 'white'))

# Update axes lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey', 
                 showline=True, linewidth=1, linecolor='black',
                 title='epochs'
                )

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey', 
                 showline=True, linewidth=1, linecolor='black',
                 title='Loss(Mean squared error)'
                )

# Set figure title
fig.update_layout(title=dict(text="Training loss", 
                             font=dict(color='black')),
                  legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
                 )

fig.show()

# LSTM
model=Sequential()
model.add(LSTM(20,activation='relu',input_shape=(None, 1),return_sequences=True))
model.add(LSTM(20,activation='relu',return_sequences=True))
model.add(LSTM(20,activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam',loss='mse')
model.summary()
history_LSTM = model.fit(X_train, y_train, epochs = 100, validation_data = (X_val, y_val), batch_size=5,)


y_predict = model.predict(X_train)
r2_y_predict = r2_score(y_train, y_predict) 
print("R2 :", r2_y_predict)
model.evaluate(X_train, y_train)

model = Sequential([
                   Flatten(input_shape = [X_train.shape[-1],1], ),
                    Dense(20),
                    Dense(20),
                    Dense(20),
                    Dense(1)
])
model.compile(optimizer='adam',loss='mse')
model.summary()
history_DL = model.fit(X_train, y_train, epochs = 100, validation_data = (X_val, y_val), batch_size=5,)

y_predict = model.predict(X_train)
r2_y_predict = r2_score(y_train, y_predict) 
print("R2 :", r2_y_predict)
model.evaluate(X_train, y_train)

# Visualization
import plotly 
import plotly.express as px
import plotly.graph_objects as go
print('plotly: %s' % plotly.__version__) # print version
history = pd.DataFrame({'RNN' : [], 'LSTM': [], 'DL' : []})
history['RNN'] = history_RNN_PCA.history['loss']
history['LSTM'] = history_LSTM.history['loss']
history['DL'] = history_DL.history['loss']
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(range(0,len(history))),
                         y=history['RNN'],
                         mode='lines',
                         name='RNN',
                         opacity=0.8,
                         line=dict(color='red', width=2)
                        ))
fig.add_trace(go.Scatter(x=np.array(range(0,len(history))),
                         y=history['LSTM'],
                         mode='lines',
                         name='LSTM',
                         opacity=0.8,
                         line=dict(color='blue', width=2)
                        ))
fig.add_trace(go.Scatter(x=np.array(range(0,len(history))),
                         y=history['DL'],
                         mode='lines',
                         name='DL',
                         opacity=0.8,
                         line=dict(color='green', width=2)
                        ))


# Change chart background color
fig.update_layout(dict(plot_bgcolor = 'white'))

# Update axes lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey', 
                 showline=True, linewidth=1, linecolor='black',
                 title='epochs'
                )

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey', 
                 showline=True, linewidth=1, linecolor='black',
                 title='Loss(Mean squared error)'
                )

# Set figure title
fig.update_layout(title=dict(text="Training loss", 
                             font=dict(color='black')),
                  legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
                 )

fig.show()

# Predict the result on training data
pred_train = model.predict(principalDf)
##### Step 8 - Model Performance Summary

print("")
print('-------------------- Model Summary --------------------')
model.summary() # print model summary
print("")
print('-------------------- Weights and Biases --------------------')
print("Note, the last parameter in each layer is bias while the rest are weights")
print("")

print("")
print('---------- Evaluation on Training Data ----------')
print("MSE: ", mean_squared_error(target, pred_train))
print("")

# Visualization

import plotly 
import plotly.express as px
import plotly.graph_objects as go
print('plotly: %s' % plotly.__version__) # print version
fig = go.Figure()
fig.add_trace(go.Scatter(x=raw_data.iloc[:,1][59+2:145],
                         y=target*data['Feeding_vol'].std()+data['Feeding_vol'].mean(),
                         mode='lines',
                         name='Actual (Train)',
                         opacity=0.8,
                         line=dict(color='black', width=2)
                        ))
fig.add_trace(go.Scatter(x=raw_data.iloc[:,1][59+2:145],
                         y=(pred_train.reshape(-1)*data['Feeding_vol'].std()+data['Feeding_vol'].mean()),
                         mode = 'lines+markers',
                         name='Predicted (diff:1, Timestep : 2) (Train)',
                         opacity=0.8,
                         line=dict(color='red', width=1)
                        ))


# Change chart background color
fig.update_layout(dict(plot_bgcolor = 'white'))

# Update axes lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey', 
                 showline=True, linewidth=1, linecolor='black',
                 title='Elapsed hr'
                )

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey', 
                 showline=True, linewidth=1, linecolor='black',
                 title='Feeding Q (mL/hr)'
                )

# Set figure title
fig.update_layout(title=dict(text="Feeding flow rate", 
                             font=dict(color='black')),
                  legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
                 )

fig.show()

FeFraw_data.iloc[:,1][59+timestep:145]

pred_test =model.predict(test_PCA)

model.evaluate(test_PCA, y_test)

# Visualization (test data)
timestep = 2
fig = go.Figure()
fig.add_trace(go.Scatter(x=raw_test.iloc[:,1][59+timestep:145],
                         y=y_test*test['Feeding_vol'].std()+test['Feeding_vol'].mean(),
                         mode='lines',
                         name='Actual (Test)',
                         opacity=0.8,
                         line=dict(color='black', width=2)
                        ))
fig.add_trace(go.Scatter(x=raw_test.iloc[:,1][59+timestep:145],
                         y=(pred_test.reshape(-1)*test['Feeding_vol'].std()+test['Feeding_vol'].mean()),
                         mode = 'lines+markers',
                         name='Predicted (diff:1, Timestep : 2) (Test)',
                         opacity=0.8,
                         line=dict(color='red', width=1)
                        ))


# Change chart background color
fig.update_layout(dict(plot_bgcolor = 'white'))

# Update axes lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey', 
                 showline=True, linewidth=1, linecolor='black',
                 title='Elapsed hr'
                )

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey', 
                 showline=True, linewidth=1, linecolor='black',
                 title='Feeding Q (mL/hr)'
                )

# Set figure title
fig.update_layout(title=dict(text="Feeding flow rate", 
                             font=dict(color='black')),
                  legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
                 )

fig.show()

def data_gen():
    while True:
        x = np.random.rand(5, 1,1)  # batch x time x features
        yield x, x[:, :, 0] * x[:, :, 1] < 0.25

def var_importance(model):
    g = data_gen()
    x = np.concatenate([next(g)[0] for _ in range(50)]) # Get a sample of data
    orig_out = model.predict(x)
    for i in range(3):  # iterate over the three features
        new_x = x.copy()
        perturbation = np.random.normal(0.0, 0.2, size=new_x.shape[:2])
        new_x[:, :, i] = new_x[:, :, i] + perturbation
        perturbed_out = model.predict(new_x)
        effect = ((orig_out - perturbed_out) ** 2).mean() ** 0.5
        print(f'Variable {i+1}, perturbation effect: {effect:.4f}')
var_importance(model)


import shap
import numpy as np

# select a set of background examples to take an expectation over
background = principalDf.iloc[np.random.choice(principalDf.shape[0], 80, replace=False)]

# explain predictions of the model on three images
explainer = shap.GradientExplainer(model, background)
# ...or pass tensors directly
# e = shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), background)
shap_values = explainer.shap_values(X_test[:10])

X_test

"""
Network Architecture
"""
from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import (
    Activation,
    LSTM,
    Dense,
    Dropout,
    Flatten,
    BatchNormalization,
)

def net_arch(net_in, n_vocab):
    model = Sequential()

    # 256 - dimensionality of the output space
    model.add(
        LSTM(
            256,
            input_shape=net_in.shape[1:],
            return_sequences=True,
            recurrent_dropout=0.3,
        )
    )
    model.add(LSTM(256))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))
    model.add(Dense(128))
    model.add(Activation("relu"))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))
    model.add(Dense(n_vocab))
    model.add(Activation("softmax"))

    model.compile(loss="categorical_crossentropy", optimizer="adam")
    return model

from tensorflow.keras.callbacks import ModelCheckpoint


def train(model, net_in, net_out, epochs):
    filepath = "weights.best.music3.hdf5"
    checkpoint = ModelCheckpoint(
        filepath, monitor="loss", verbose=0, save_best_only=True
    )
    model.fit(net_in, net_out, epochs=epochs, batch_size=32, callbacks=[checkpoint])

epochs = 30
model = net_arch(features, target)
train(model, features, target, epochs)

def split_series(series, n_past, n_future):
  #
  # n_past ==> no of past observations
  #
  # n_future ==> no of future observations 
  #
  X, y = list(), list()
  for window_start in range(len(series)):
    past_end = window_start + n_past
    future_end = past_end + n_future
    if future_end > len(series):
      break
    # slicing the past and future parts of the window
    past, future = series[window_start:past_end, :], series[past_end:future_end, :]
    X.append(past)
    y.append(future)
  return np.array(X), np.array(y)
n_past = 10
n_future = 5 
n_features = 8
X_train, y_train = split_series(data_filtered.values,n_past, n_future)
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1],n_features))
y_train = y_train.reshape((y_train.shape[0], y_train.shape[1], n_features))

# E1D1
# n_features ==> no of features at each timestep in the data.
#
encoder_inputs = tf.keras.layers.Input(shape=(features.shape[-1],1))
encoder_l1 = tf.keras.layers.LSTM(100, return_state=True)
encoder_outputs1 = encoder_l1(encoder_inputs)

encoder_states1 = encoder_outputs1[1:]

#
decoder_inputs = tf.keras.layers.RepeatVector(n_future)(encoder_outputs1[0])

#
decoder_l1 = tf.keras.layers.LSTM(100, return_sequences=True)(decoder_inputs,initial_state = encoder_states1)
decoder_outputs1 = tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(n_features))(decoder_l1)

#
model_e1d1 = tf.keras.models.Model(encoder_inputs,decoder_outputs1)

#
model_e1d1.summary()